- .env
I have connected 'Mongodb cluster'
> feat: Mongodb cluster connect

- src/amuwiki/amuwiki.controller.spec.ts
- src/amuwiki/amuwiki.controller.ts
- src/amuwiki/amuwiki.module.ts
- src/amuwiki/amuwiki.service.spec.ts
- src/amuwiki/amuwiki.service.ts
- src/app.module.ts
> Wiki Folder

- package-lock.json
- package.json
- src/app.module.ts
- src/user/dto/user.dto.ts
- src/user/user.controller.ts
- src/user/user.module.ts
- src/user/user.schema.ts
- src/user/user.service.ts
I have made this basic Login part 
and I installed this two library
please npm install again
"class-transformer": "^0.5.1",
"class-validator": "^0.14.0",
> feat: Basic Login part built

- package-lock.json
- package.json
- src/amuwiki/amuwiki.controller.ts
- src/amuwiki/amuwiki.module.ts
- src/amuwiki/amuwiki.service.ts
- src/app.module.ts
- src/user/dto/verifyEmail.dto.ts
- src/user/user.controller.ts
- src/user/user.service.ts
I installed "nodemailer": "^6.9.1"
please check.
thank you.
> feat:  Add method of sending verifying code to email to Signup part

- src/user/dto/user.dto.ts
- src/user/schemas/user.schema.ts
- src/user/user.controller.ts
- src/user/user.service.ts
it needs some refactoring and almost done.
thank you. :)
> feat: Rebuilding Sinup part using verify method

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
I rebuilt login part
thank you.
> feat: Rebuilding Login part

- .eslintrc.js
- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/profile/dto/basicProfile.dto.ts
- src/profile/dto/createProfile.dto.ts
- src/profile/dto/detailProfile.dto.ts
- src/profile/dto/editProfile.dto.ts
- src/profile/profile.controller.ts
- src/profile/profile.module.ts
- src/profile/profile.service.ts
- src/profile/schemas/profile.schema.ts
> feat: Building Profile search part

- src/profile/profile.controller.ts
- src/profile/profile.service.ts
> feat: Building Profile creat part

- src/app.module.ts
- src/profile/profile.controller.ts
- src/profile/profile.service.ts
> feat: Building Profile edit part

- src/auth/auth.controller.ts
- src/auth/auth.module.ts
> feat: Building Authorization part

- package-lock.json
- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
- src/auth/dto/deleteuser.dto.ts
- src/user/user.service.ts
please check.
I finished all my building part
and I have checked there is no problem with using our application.
So now after close this issue I'll do refactoring code which part is user file and auth file.
thank you.
> feat: Building Membership withdrawl part

- src/amuwiki/amuwiki.controller.ts
- src/amuwiki/amuwiki.service.ts
> Refactoring wiki file

- src/auth/auth.controller.ts
I have corrected the spelling from "withdrawl" to "withdrawal."
> feat: Correcting the spelling error

- src/app.module.ts
- src/post/dto/createPost.dto.ts
- src/post/post.controller.ts
- src/post/post.module.ts
- src/post/post.service.ts
> feat: Building Post create part

- src/post/post.controller.ts
- src/post/post.service.ts
> feat: Building Post delete part

- src/post/dto/editPost.dto.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> feat: Building Post edit part

- src/user/user.controller.ts
- src/user/user.module.ts
- src/user/user.service.ts
and I finished Refactoring.
Thank you.
> feat: Refactoring user file

- src/auth/auth.controller.ts
- src/auth/auth.module.ts
- src/auth/auth.service.ts
and I fished refactoring
Thank you.
> feat: Refactoring auth file

- package-lock.json
- package.json
- src/profile/dto/basicProfile.dto.ts
- src/profile/dto/uploadProfile.dto.ts
- src/profile/profile.controller.ts
- src/profile/profile.module.ts
- src/profile/profile.service.ts
- src/profile/schemas/profile.schema.ts
I installed "fastify-multipart": "^5.4.0"
> feat: error frofile image upload

- src/post/dto/editPost.dto.ts
- src/post/post.controller.ts
- src/post/post.module.ts
- src/post/post.service.ts
> feat: 2nd Refactoring post file

- package.json
- src/main.ts
- src/post/dto/editPost.dto.ts
- src/post/post.controller.ts
- src/post/post.module.ts
- src/post/post.service.ts
- src/profile/profile.controller.ts
- src/profile/profile.module.ts
- src/profile/profile.service.ts
- src/profile/schemas/profile.schema.ts
- src/user/schemas/user.schema.ts
port number changed, file upload added
> feat:change Profile

- src/post/post.controller.ts
- src/post/post.service.ts
Added 'url' and wrote 'readonly'.
> feat: 3rd Refactoring post file

- src/amuwiki/amuwiki.service.ts
- src/post/post.controller.ts
- src/post/post.module.ts
I built findMyPosts,
and we connected 'elasticsearch'
Thank you.
> feat: Building Post's mypost part

- src/post/post.controller.ts
- src/post/post.module.ts
- src/post/post.service.ts
Changed editPost, deletePost code in post.service.ts
> feat: 4th Refactoring post file

- README.md
> feat: Retouching ReadMe

- .dockerignore
- docker-compose.yml
- dockerfile
- elasticsearch.dockerfile
We finally made docker-compose.yml
but we have another issue for monstache.
So today we have last monstache's issue for the test.
> feat: Composing Dockercompose-practice

- src/amuwiki/amuwiki.service.ts
> Updating Amuwiki Search

- src/amuwiki/amuwiki.service.ts
- src/post/post.controller.ts
- src/post/post.service.ts
I edited
amuwiki.service.ts
-- findMyPosts
post.service.ts
-- findMyPost
-- createPost
-- editPost
-- deletePost
and we finished to test on local environment
> feat: Changing contributors from 'nickname' to 'email'

- src/amuwiki/amuwiki.service.ts
- src/post/dto/detailpost.dto.ts
- src/post/post.controller.ts
- src/post/post.service.ts
> feat: 5th Refactoring post file

- src/amuwiki/amuwiki.controller.ts
- src/amuwiki/amuwiki.service.ts
> Refactoring Amuwiki Search

- src/profile/profile.controller.ts
- src/profile/profile.service.ts
> feat:Refactoring Profile

- src/post/post.controller.ts
- src/post/post.service.ts
> feat: 6th Refactoring Post part

- src/auth/auth.controller.ts
- src/auth/auth.service.ts
- src/user/user.controller.ts
- src/user/user.service.ts
and I deleted logout part
cause we decide to logout flow
process on the frontEnd part
and changed the handleLogin part
and handle Withdrawal part too.
Thank you.
> feat: Refactoring Auth and User file

- src/auth/auth.service.ts
- src/user/user.service.ts
I got the messages from frontEnd which is not working about statusCode
I changed errorHandler to tryCatch
> feat: Refactoring errorHandler

- src/profile/profile.controller.ts
- src/profile/profile.service.ts
> feat:Refactoring Image Upload

- src/user/user.service.ts
I installed nothin.
thank you.
> feat: Refactoring bug code

- my-project-amu-b74433c069fd.json
- package-lock.json
- package.json
- src/profile/profile.module.ts
- src/profile/profile.service.ts
- src/profile/storage.module.ts
Due to the issue of storing data on each local instance caused by load balancing between two instances, we decided to switch to a cloud-based storage system for retrieving profile information.
> feat: Changing Storage to Google cloud storage

- docker-compose.yml
> feat:Updating Docker-compose.yml
